version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./fitness-data/postgres-data:/var/lib/postgresql/data    

  fithead:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./fitness-data:/app/fitness-data