version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./fitness-data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fithead:
    build: .
    platform: linux/amd64
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    ports:
      - "5008:5000"
    depends_on:
      - db
    volumes:
      - ./fitness-data:/app/fitness-data
